<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-23T17:56:01 IST" name="Default suite" finished-at="2023-01-23T17:56:15 IST" duration-ms="14035">
    <groups>
    </groups>
    <test started-at="2023-01-23T17:56:01 IST" name="Default test" finished-at="2023-01-23T17:56:15 IST" duration-ms="14035">
      <class name="com.XYZ.tests.ManagerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.XYZ.tests.ManagerTest@342c38f8]" started-at="2023-01-23T17:56:01 IST" name="setUp" finished-at="2023-01-23T17:56:11 IST" duration-ms="9935" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyAddCustomers()[pri:0, instance:com.XYZ.tests.ManagerTest@342c38f8]" started-at="2023-01-23T17:56:11 IST" name="verifyAddCustomers" finished-at="2023-01-23T17:56:14 IST" duration-ms="2937" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddCustomers -->
        <test-method signature="verifyOpenAccount()[pri:0, instance:com.XYZ.tests.ManagerTest@342c38f8]" started-at="2023-01-23T17:56:14 IST" name="verifyOpenAccount" finished-at="2023-01-23T17:56:15 IST" duration-ms="825" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [By.xpath: /html/body/div/div/div[2]/div/div[1]/button[1]] but found [By.xpath: /html/body/div/div/div[2]/div/div[2]/div/div/form/button]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [By.xpath: /html/body/div/div/div[2]/div/div[1]/button[1]] but found [By.xpath: /html/body/div/div/div[2]/div/div[2]/div/div/form/button]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotSame(Assert.java:1033)
at org.testng.Assert.assertSame(Assert.java:981)
at org.testng.Assert.assertSame(Assert.java:992)
at com.XYZ.pages.ManagerPage.openAccount(ManagerPage.java:116)
at com.XYZ.tests.ManagerTest.verifyOpenAccount(ManagerTest.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOpenAccount -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.XYZ.tests.ManagerTest@342c38f8]" started-at="2023-01-23T17:56:15 IST" name="teardown" finished-at="2023-01-23T17:56:15 IST" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.XYZ.tests.ManagerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
